---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart libvirtd
  ansible.builtin.systemd_service:
    name: libvirtd
    state: restarted

- name: Restart novnc
  ansible.builtin.systemd_service:
    name: novnc
    state: restarted
