---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart libvirtd
  ansible.builtin.systemd_service:
    name: libvirtd
    state: restarted

- name: Restart novnc instances
  ansible.builtin.systemd_service:
    name: "novnc@{{ item.name }}"
    state: restarted
  loop: "{{ qemu_host_novnc_vms }}"
  loop_control:
    label: "{{ item.name }}"
