---
- name: Prepare
  hosts: all
  tasks:
    - name: Enable EPEL repository
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Install websockify (noVNC dependency)
      ansible.builtin.dnf:
        name: python3-websockify
        state: present

    - name: Install novnc package
      ansible.builtin.dnf:
        name: novnc
        state: present
