---
- name: Install QEMU VM template systemd unit
  ansible.builtin.template:
    src: qemu-vm@.service.j2
    dest: /etc/systemd/system/qemu-vm@.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd

- name: Install swtpm template systemd unit
  ansible.builtin.template:
    src: swtpm@.service.j2
    dest: /etc/systemd/system/swtpm@.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
