---
- name: Write bridge.conf
  ansible.builtin.template:
    src: bridge.conf.j2
    dest: "{{ create_vm_bridge_conf }}"
    owner: root
    group: root
    mode: "0644"
  when: >-
    _create_vm_active_vms | selectattr('net_mode', 'defined')
                          | selectattr('net_mode', 'equalto', 'bridge')
                          | list | length > 0
    or (_create_vm_active_vms | rejectattr('net_mode', 'defined') | list | length > 0
        and create_vm_default_net_mode == 'bridge')
