---
- name: Prepare
  hosts: all
  tasks:
    - name: Install pip
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Install websockify
      ansible.builtin.pip:
        name: websockify
        state: present
